package com.eric.financas.audit;

public enum AuditAction {
    REGISTRO,
    LOGIN_SUCESSO,
    LOGIN_FALHA,
    LOGOUT,
    NOVO_LANCAMENTO,
    EDITAR_LANCAMENTO,
    EXCLUIR_LANCAMENTO,
    TRANSFERENCIA,
    ALOCACAO_POUPANCA,
    CATEGORIA_CRIADA,
    CATEGORIA_EDITADA,
    CATEGORIA_EXCLUIDA,
    CONTA_CRIADA,
    CONTA_EDITADA,
    CONTA_EXCLUIDA
}
